# Not found
ERROR_NOT_FOUND = 404
MSG_NOT_FOUND = 'Not found'

# Internal Server Error
ERROR_INTERNAL_SERVER = 500
MSG_INTERNAL_SERVER = 'Internal Server Error' 

# Status OK
STATUS_OK = 200

# VALIDATE ERROR
ERROR_VALIDATE = 1001
MSG_VALIDATE = 'Validate data error'

# NOT LOGIN
# ERROR_TOKEN_EXPIRED = 1002
# MSG_TOKEN_EXPIRED = 'Not yet login'
ERROR_NOT_LOGIN = 1002
MSG_NOT_LOGIN = 'Not yet login'

# LOGIN FAIL
ERROR_LOGIN_FAILED = 1004
MSG_LOGIN_FAILED = 'Username or Password incorrect'

# UPDATE TOKEN FAIL
ERROR_UPDATE_TOKEN = 1005
MSG_UPDATE_TOKEN = 'Updating token fails'

# PASSWORD INCORRECT
ERROR_PASSWORD_INCORRECT = 1006
MSG_PASSWORD_INCORRECT = 'Password incorrect'

# USERNAME ALREADY USED
ERROR_USERNAME_USED = 2001
MSG_USERNAME_USED = 'Username already used'

# EMAIL ALREADY EXIST
ERROR_EMAIL_EXIST = 2002
MSG_EMAIL_EXIST = 'Email already exist'

# CREATE USER ERROR
ERROR_INSERT_USER = 2003
MSG_INSERT_USER = 'Create new user failed'

# GET USER ERROR
ERROR_GET_USER = 2004
MSG_GET_USER = 'Get information of a user failed'

# GET ALL POST USER ERROR
ERROR_GET_ALL_POST_USER_FAILED = 2500
MSG_GET_ALL_POST_USER_FAILED = 'Get all post of user error'

# GET ALL POST ERROR
ERROR_GET_ALL_POST_FAILED = 2501
MSG_GET_ALL_POST_FAILED = 'Get all post error'

# CREATE POST ERROR
ERROR_CREATE_POST_FAILED = 2502
MSG_CREATE_POST_FAILED = 'Create new post error'

# UPDATE POST ERROR
ERROR_UPDATE_POST_FAILED = 2503
MSG_UPDATE_POST_FAILED = 'Update post error'

# DELETE POST ERROR
ERROR_DELETE_POST_FAILED = 2504
MSG_DELETE_POST_FAILED = 'Delete post error'

# GET A POST ERROR
ERROR_GET_A_POST_FAILED = 2505
MSG_GET_A_POST_FAILED = 'get a post error'

# SEARCH POST ERROR
ERROR_SEARCH_POST_FAILED = 2506
MSG_SEARCH_POST_FAILED = 'Search post error'

#GET ID COMMENT NOT EXIST
ERROR_GET_ID_COMMENT_NOT_EXIST = 3001
MSG_GET_ID_COMMENT_NOT_EXIST = 'ID comment not exist'

# CREATE COMMENT ERROR
ERROR_CREATE_COMMENT_FAILED = 3002
MSG_CREATE_COMMENT_FAILED = 'Create new comment error'
MSG_CREATE_COMMENT_SUCCESS = 'Write a comment successfully'

# UPDATE COMMENT ERROR
ERROR_UPDATE_COMMENT_FAILED = 3003
MSG_UPDATE_COMMENT_FAILED = 'Update comment error'
MSG_UPDATE_COMMENT_SUCCESS = 'Update a comment successfully'

# DELETE COMMENT ERROR
ERROR_DELETE_COMMENT_FAILED = 3004
MSG_DELETE_COMMENT_FAILED = 'Delete comment error'
MSG_DELETE_COMMENT_SUCCESS = 'Delete a comment successfully'

# ID USER OR ID POST IS WRONG
ERROR_ID_USER_OR_ID_POST_IS_WRONG = 3005
MSG_ID_USER_OR_ID_POST_IS_WRONG = 'Wrong ID user or ID post'

# GET ALL COMMENT USER ERROR
ERROR_GET_ALL_COMMENT_USER_ERROR = 3006
MSG_GET_ALL_COMMENT_USER_ERROR = 'Get comments of user fail'

# GET ALL COMMENT POST ERROR
ERROR_GET_ALL_COMMENT_POST_ERROR = 3007
MSG_GET_ALL_COMMENT_POST_ERROR = 'Get comments of post fail'

